---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2023/3/3 14:37
--- 1. 参数列表
--- 1.1 优惠券id
local voucherId = ARGV[1]
--- 1.2 用户id
local userId = ARGV[2]
--- 1.3 订单id
local orderId = ARGV[3]
--- 数据key
--- 库存key  通过该key获取 库存,  lua脚本使用 .. 来拼接字符串
local stock = 'seckill:stock:' .. voucherId
--- 订单key
local order = 'seckill:order:' .. userId

--- 脚本业务
--- 判断库存是否充足
if(tonumber(redis.call('get',stock)) <= 0) then
    --- 库存不充足,返回1
    return 1
end
--- 判断用户是否下单, 用户下单保存在set里面（利用set的唯一属性）,等于1 说明存在
if(redis.call('SISMEMBER',order,userId) == 1) then
    --- 等于1，说明是重复下单
    return 2
end
--- 此时，库存充足，保证一人一单  扣库存  incrby - 1
redis.call('incrby', stock,-1)
--- 保存该订单,
redis.call('sadd',order,userId)
--- 发送消息,将订单的所用信息发送,用户id，优惠券id，自己的id（订单id）
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0

























